Global:
  ManageImages: true
  BootMountPoint: /boot/efi
  DracutConfDir: /etc/zfsbootmenu/dracut.conf.d
  PostHooksDir: /etc/zfsbootmenu/generate-zbm.post.d
  DracutFlags:
    - "--no-early-microcode"
Components:
   Enabled: false
EFI:
  ImageDir: /boot/efi/EFI/zbm
  Versions: 2
  Enabled: true
#   The path to a bitmap image file (BMP) to use as a splash image before ZFSBootMenu loads. 
#   Only works if using systemd-boot's EFI stub loader. The ZFSBootMenu logo is available in 
#   BMP format at ``/usr/share/examples/zfsbootmenu/splash.bmp``.
  # SplashImage: /etc/zfsbootmenu/splash.bmp
Kernel:
  CommandLine: ro quiet loglevel=0
SecureBoot:
  SignBackup: true
  SignMethod: sbsign
  KeyFileName: /etc/refind.d/keys/refind_local.key
  CrtFileName: /etc/refind.d/keys/refind_local.crt
